# Generated by Django 4.2.7 on 2023-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
